apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: collab-svc
  namespace: default
spec:
  owner:
    projectName: doclet

  componentType: deployment/service
  autoDeploy: true

  workflow:
    name: docker
    systemParameters:
      repository:
        url: "https://github.com/VajiraPrabuddhaka/doclet-app.git"
        revision:
          branch: "main"
        appPath: "/"
    parameters:
      docker:
        context: "/"
        filePath: "/services/collab/Dockerfile"

  parameters:
    exposed: true
    replicas: 1
    port: 8090
