apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: frontend-workload
  namespace: default
spec:
  containers:
    main:
      image: host.k3d.internal:10082/doclet-frontend-image:v1-8c4cda2f
  owner:
    componentName: frontend
    projectName: doclet
