apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: frontend-staging
  namespace: default
spec:
  environment: staging
  owner:
    componentName: frontend
    projectName: doclet
  releaseName: frontend-20260209-1
