apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: frontend-development
  namespace: default
spec:
  environment: development
  owner:
    componentName: frontend
    projectName: doclet
  releaseName: frontend-8c4cda2f
